import { useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { LeadFormData } from '@/utils/leadValidation';

export const useLeadSubmission = () => {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: LeadFormData) => {
      // Insert lead into database (reference number auto-generated by trigger)
      const { data: lead, error: insertError } = await supabase
        .from('leads')
        .insert([{
          full_name: data.full_name,
          email: data.email,
          phone: data.phone,
          organization: data.organization,
          country: data.country,
          training_interest: data.training_interest,
          source: data.source || 'Website',
          message: data.message,
          status: 'new',
          reference_number: '', // Will be auto-generated by trigger
        }])
        .select()
        .single();

      if (insertError) throw insertError;

      // Log activity: Lead created
      await supabase.from('activities').insert([{
        lead_id: lead.id,
        activity_type: 'note',
        summary: 'Lead Created via Website Form',
        details: `Lead submitted from website inquiry form. Training interest: ${data.training_interest}`,
      }]);

      return lead;
    },
    onSuccess: (lead) => {
      toast({
        title: "Thank you for your interest!",
        description: `Your inquiry has been received. Reference: ${lead.reference_number}`,
      });
      queryClient.invalidateQueries({ queryKey: ['leads'] });
    },
    onError: (error) => {
      console.error('Error submitting lead:', error);
      toast({
        title: "Submission Failed",
        description: "There was an error submitting your inquiry. Please try again.",
        variant: "destructive",
      });
    },
  });
};
