// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gppohyyuggnfecfabcyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwcG9oeXl1Z2duZmVjZmFiY3l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1OTE1MTEsImV4cCI6MjA3MzE2NzUxMX0.j6y0D8smJAwuC9zw0jzD40TXK2x_go0E2d1gynQC9xk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});